version: 2
updates:
  - package-ecosystem: 'nuget'
    open-pull-requests-limit: 2
    directory: '/Holtz.DesignPattern.Adapter/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'nuget'
    open-pull-requests-limit: 2
    directory: '/Holtz.DesignPattern.Bridge/'
    schedule:
      interval: 'weekly'
