# @name createIndex
POST http://localhost:5182/api/users/create-index?indexName=users2 HTTP/1.1
content-type: application/json

### 
# @name addUser
POST http://localhost:5182/api/users HTTP/1.1
content-type: application/json

{
    "id": 1515,
    "firstName": "Henrique",
    "lastName": "Holtz"
}

###
@userId = {{ addUser.request.body.id }}

###
# @name getAllUsers
GET http://localhost:5182/api/users HTTP/1.1

### 
# @name getUser
GET http://localhost:5182/api/users/{{userId}} HTTP/1.1

### 
# @name updateUser
PUT http://localhost:5182/api/users HTTP/1.1
content-type: application/json

{
    "id": 1515,
    "firstName": "Henrique",
    "lastName": "Holtz Updated"
}

### 
# @name deleteUser
DELETE http://localhost:5182/api/users/{{userId}} HTTP/1.1