version: '3.4'

services:
  holtz.dapper.api:
    image: ${DOCKER_REGISTRY-}holtzdapperapi
    build:
      context: .
      dockerfile: Holtz.Dapper.Api/Dockerfile
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P@ssword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    volumes:
      - ./sql/:/usr/src/sql/