FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# DockerHub: Build and push (Arm64 + Amd64)
# docker buildx build --push --platform=linux/amd64,linux/arm64 -t henriqueholtz/holtz-docker-image-base:sdk_8.0 -f ./Dockerfile.Net8.Sdk .

