version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb

  catalog.api:
    image: ${DOCKER_REGISTRY-}holtzcatalogmicroservicesapi
    build:
      context: .
      dockerfile: Holtz.Catalog.Microservices.Api/Dockerfile

volumes:
  mongo_data:
