name: Holtz.DesignPattern.Bridge.Tests

on:
  push:
    branches: [master]
    paths:
      - 'Holtz.DesignPattern.Bridge/**'
  pull_request:
    branches: [master]
    paths:
      - 'Holtz.DesignPattern.Bridge/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Tests
        run: dotnet test Holtz.DesignPattern.Bridge/Holtz.DesignPattern.Bridge.Tests/Holtz.DesignPattern.Bridge.Tests.csproj
