name: Holtz_DesignPattern_AbstractFactory_Tests

on:
  push:
    branches: [master]
    paths:
      - 'Holtz.DesignPattern.AbstractFactory/**'
  pull_request:
    branches: [master]
    paths:
      - 'Holtz.DesignPattern.AbstractFactory/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Tests
        run: dotnet test Holtz.DesignPattern.AbstractFactory/Holtz.DesignPattern.AbstractFactoryTests/Holtz.DesignPattern.AbstractFactoryTests.csproj
