name: Holtz.DesignPattern.SimpleFactory.Tests

on:
  push:
    branches: [master]
    paths:
      - 'Holtz.DesignPattern.SimpleFactory/**'
  pull_request:
    branches: [master]
    paths:
      - 'Holtz.DesignPattern.SimpleFactory/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Tests
        run: dotnet test Holtz.DesignPattern.SimpleFactory/Holtz.DesignPattern.SimpleFactory.Tests/Holtz.DesignPattern.SimpleFactory.Tests.csproj
